@extends('layout.layout')

@section('title', 'The Peninsula Island')

@section('content')
<div class="background-radial-blur -translate-x-100 -translate-y-25"></div>
<p class="text-5xl text-center font-semibold"><span class="text-lime-600">Discover More </span>About This Place</p>
<x-search-bar accent="text-lime-600"></x-search-bar>
<div class="grid grid-cols-1 mt-10 gap-4">
    <x-blogs-card href="/blogs/blogs-detail" date="19 October 2025" image="img/placeholder.jpg" title="Pura Bias Tugel a Temple in Peninsula Island">Lorem ipsum dolor sit amet consectetur adipisicing elit. Est voluptatum similique aliquid cupiditate distinctio minus iure sint maxime magnam? Reprehenderit atque provident sunt accusantium laboriosam dolorum nihil debitis quas consequatur quasi quisquam mollitia officiis dolorem, facilis explicabo porro maiores, culpa rerum quia laudantium ullam. Molestiae incidunt, provident fugiat temporibus, nulla eius in, vero blanditiis aspernatur aliquam tenetur impedit cupiditate maxime consequatur dolore dolorem? Dolore, neque atque suscipit nisi sapiente velit iste modi voluptatem incidunt sint laborum ut, fuga earum ad.</x-blogs-card>
    <x-blogs-card href="/blogs/blogs-detail" date="19 October 2025" image="img/placeholder.jpg" title="Pura Bias Tugel a Temple in Peninsula Island">Lorem ipsum dolor sit amet consectetur adipisicing elit. Est voluptatum similique aliquid cupiditate distinctio minus iure sint maxime magnam? Reprehenderit atque provident sunt accusantium laboriosam dolorum nihil debitis quas consequatur quasi quisquam mollitia officiis dolorem, facilis explicabo porro maiores, culpa rerum quia laudantium ullam. Molestiae incidunt, provident fugiat temporibus, nulla eius in, vero blanditiis aspernatur aliquam tenetur impedit cupiditate maxime consequatur dolore dolorem? Dolore, neque atque suscipit nisi sapiente velit iste modi voluptatem incidunt sint laborum ut, fuga earum ad.</x-blogs-card>
    <x-blogs-card href="/blogs/blogs-detail" date="19 October 2025" image="img/placeholder.jpg" title="Pura Bias Tugel a Temple in Peninsula Island">Lorem ipsum dolor sit amet consectetur adipisicing elit. Est voluptatum similique aliquid cupiditate distinctio minus iure sint maxime magnam? Reprehenderit atque provident sunt accusantium laboriosam dolorum nihil debitis quas consequatur quasi quisquam mollitia officiis dolorem, facilis explicabo porro maiores, culpa rerum quia laudantium ullam. Molestiae incidunt, provident fugiat temporibus, nulla eius in, vero blanditiis aspernatur aliquam tenetur impedit cupiditate maxime consequatur dolore dolorem? Dolore, neque atque suscipit nisi sapiente velit iste modi voluptatem incidunt sint laborum ut, fuga earum ad.</x-blogs-card>
    <x-blogs-card href="/blogs/blogs-detail" date="19 October 2025" image="img/placeholder.jpg" title="Pura Bias Tugel a Temple in Peninsula Island">Lorem ipsum dolor sit amet consectetur adipisicing elit. Est voluptatum similique aliquid cupiditate distinctio minus iure sint maxime magnam? Reprehenderit atque provident sunt accusantium laboriosam dolorum nihil debitis quas consequatur quasi quisquam mollitia officiis dolorem, facilis explicabo porro maiores, culpa rerum quia laudantium ullam. Molestiae incidunt, provident fugiat temporibus, nulla eius in, vero blanditiis aspernatur aliquam tenetur impedit cupiditate maxime consequatur dolore dolorem? Dolore, neque atque suscipit nisi sapiente velit iste modi voluptatem incidunt sint laborum ut, fuga earum ad.</x-blogs-card>
    <x-blogs-card href="/blogs/blogs-detail" date="19 October 2025" image="img/placeholder.jpg" title="Pura Bias Tugel a Temple in Peninsula Island">Lorem ipsum dolor sit amet consectetur adipisicing elit. Est voluptatum similique aliquid cupiditate distinctio minus iure sint maxime magnam? Reprehenderit atque provident sunt accusantium laboriosam dolorum nihil debitis quas consequatur quasi quisquam mollitia officiis dolorem, facilis explicabo porro maiores, culpa rerum quia laudantium ullam. Molestiae incidunt, provident fugiat temporibus, nulla eius in, vero blanditiis aspernatur aliquam tenetur impedit cupiditate maxime consequatur dolore dolorem? Dolore, neque atque suscipit nisi sapiente velit iste modi voluptatem incidunt sint laborum ut, fuga earum ad.</x-blogs-card>
</div>
@endsection
